version: '2'
services:

  web:
    image: nginx
    container_name: ${PROJECT_NAME}_nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - php
      - mysql
    volumes:
      - ./nginx/vhosts:/etc/nginx/conf.d
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    volumes_from:
      - code

  php:
    build: ./php/
    container_name: ${PROJECT_NAME}_php
    working_dir: /var/www
    volumes_from:
      - code

  mysql:
    build: ./mysql/
    container_name: ${PROJECT_NAME}_mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"

  code:
    image: busybox
    container_name: ${PROJECT_NAME}_code
    volumes:
      - ./www:/var/www

volumes:
  db-data:
    driver: local
